################################################################################
## @file    update-org-readme.yml
## @repo    .github
##
## @brief    Zum automatischen Aktualisieren der Organisations-README. 
##           update-org-readme.yml ist hierbei die Konfiguration der Action,
##           die das Aktualisieren übernimmt.
## 
## @author   Robert Malleschitz
## @mail     robert.malleschitz@novotechnik.de
################################################################################

name: Update Organisation README

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Token prüfen
        env:
          GH_TOKEN: ${{ secrets.ORG_PROFILE_TOKEN }}
        run: |
          gh auth status

      - name: Repositories auflisten
        env:
          GH_TOKEN: ${{ secrets.ORG_PROFILE_TOKEN }}
        run: |
          gh repo list Novotechnik --limit 100
          gh api orgs/Novotechnik/repos --jq '.[].name'
      
      - name: Repository testen
        env:
          GH_TOKEN: ${{ secrets.ORG_PROFILE_TOKEN }}
        run: |
          gh api repos/Novotechnik/p00753_tf1
      
      - name: GitHub CLI testen
        env:
          GH_TOKEN: ${{ secrets.ORG_PROFILE_TOKEN }}
        run: |
          gh api repos/Novotechnik/p00753_tf1/properties/values
          
      - name: README erzeugen
        run: |
          cat > profile/README.md << 'EOF'
           # Novotechnik GitHub

           Willkommen in der GitHub Organisation

           ## 🚀 Firmware
           - https://github.com/Novotechnik/p00753_tf1

           ## 🤖 Jenkins
           - https://github.com/Novotechnik/cicd-jenkins-sharedlib-codebeamer
           - https://github.com/Novotechnik/cicd-jenkins-sharedlib-docker
           - https://github.com/Novotechnik/cicd-jenkins-sharedlib-jenkins

           ## 🐳 Docker
           - https://github.com/Novotechnik/cicd-cmakes
           - https://github.com/Novotechnik/cicd-docker-compilers
           - https://github.com/Novotechnik/cicd-docker-packages
           - https://github.com/Novotechnik/cicd-docker-packages
           - https://github.com/Novotechnik/docker_images_compiler_gnu_arm_5_4

           ## 🛠️ Tools
           - https://github.com/Novotechnik/

           ## 🌐 Extern
           - https://github.com/Novotechnik/

           ## 📌 Sonstiges
           - https://github.com/Novotechnik/
          
           ## ✔️ Quality
           - https://github.com/Novotechnik/

      - name: Commit und Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add profile/README.md

          if git diff --staged --quiet; then
            echo "Keine Änderungen."
          else
            git commit -m "Update Organisation README"
           git push
          fi
