################################################################################
## @file    update-org-readme.yml
## @repo    .github
##
## @brief    Zum automatischen Aktualisieren der Organisations-README. 
##           update-org-readme.yml ist hierbei die Konfiguration der Action,
##           die das Aktualisieren übernimmt.
## 
## @author   Robert Malleschitz
## @mail     robert.malleschitz@novotechnik.de
################################################################################

name: Update Organisation README

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Actions erster Durchlauf
        run: echo "Hello Actions"
#      - name: Repository auschecken
#        uses: actions/checkout@v4

#      - name: README erzeugen
#        run: |
#          cat > profile/README.md << 'EOF'
          # Novotechnik GitHub

#          Willkommen in der GitHub Organisation

          ## 🚀 Software Development
          
#          - https://github.com/Novotechnik/p00753_tf1

          ## 🔧 DevOps

#          - https://github.com/Novotechnik/cicd-jenkins-sharedlib-codebeamer
#          - https://github.com/Novotechnik/cicd-jenkins-sharedlib-docker
#          - https://github.com/Novotechnik/cicd-jenkins-sharedlib-jenkins

#          EOF

#      - name: Commit und Push
#        run: |
#          git config user.name "github-actions"
#          git config user.email "github-actions@github.com"

#          git add profile/README.md

#          if git diff --staged --quiet; then
#            echo "Keine Änderungen."
#          else
#            git commit -m "Update Organisation README"
#            git push
#          fi
